version: '3.4'

services:
  chatservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__ApplicationDbContext=${ChatServiceDbConnectionString}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      - BUS_CONNECTION=${RABBITMQ_CONNECTION}
    ports:
      - "18443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BUS_CONNECTION=${RABBITMQ_CONNECTION}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  rabbitmq:
    image: "masstransit/rabbitmq"
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "FGHTRODSQALABOKJMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "/"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    image: postgis/postgis:16-3.4
    restart: always
    volumes:
      - ${APPDATA}/ChatServer/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${APPDATA}/ChatServer/redis:/root/redis
      - ${APPDATA}/ChatServer/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
